### PR TITLE
update dependency psr/log

### PR DESCRIPTION
**Pull request by l3aro**
When I try to install the package, it say

```
  Problem 1
    - team-reflex/discord-php[v6.0.0-RC4, ..., v6.0.2] require discord-php/http ^8 -> satisfiable by discord-php/http[v8.0.0, ..., v8.x-dev].
    - discord-php/http[v8.0.0, ..., v8.x-dev] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but it conflicts with your root composer.json require (2).
    - Root composer.json requires team-reflex/discord-php ^6.0 -> satisfiable by team-reflex/discord-php[v6.0.0-RC4, v6.0.0, v6.0.1, v6.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### CODE REVIEW

**Comment by davidcole1340** [comment]
This just seems like folder structure and type hinting updates, should be OK. Thanks!

**Comment by l3aro** [comment]
> This just seems like folder structure and type hinting updates, should be OK. Thanks!

Plan to release this PR anytime soon? I dire need it for installing in my repo @davidcole1340

**Comment by davidcole1340** [comment]
> > This just seems like folder structure and type hinting updates, should be OK. Thanks!
> 
> Plan to release this PR anytime soon? I dire need it for installing in my repo @davidcole1340

Done in v9.0.6

**Comment by l3aro** [comment]
Sweet! Thank you, sir @davidcole1340

**Pull request merged**
